Make KCP's testutils/NetworkUtils.getRandomAvailablePort work with static port interceptor
Summary:
`NetworkUtils.getRandomAvailablePort` now sets the system property `com.uber.fievel.testing.available.port.{port}` to true
which then allows this port to be used by the server and is not blocked by `SunNioNetInterceptor`.

Also, mark `NetworkUtils.getRandomAvailablePort` as `synchronized`

__Before:__
```
$ bazel test //data/kafka/uforwarder:integration_test_main --test_filter com.uber.data.kafka.consumerproxy.UforwarderIntegrationTests

3efa077884cee8e9efe662a/jetty-docbase.0.15142831797072702928/],STOPPED}
21:51:06.841 [Thread-7] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.context.ApplicationContextException: Failed to start bean 'grpcServerRunner'; nested exception is java.lang.RuntimeException: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:62932
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[org_springframework_spring_context-5.3.30.jar:5.3.30]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[org_springframework_spring_context-5.3.30.jar:5.3.30]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:357) ~[org_springframework_spring_context-5.3.30.jar:5.3.30]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:156) ~[org_springframework_spring_context-5.3.30.jar:5.3.30]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:124) ~[org_springframework_spring_context-5.3.30.jar:5.3.30]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) ~[org_springframework_spring_context-5.3.30.jar:5.3.30]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[org_springframework_spring_context-5.3.30.jar:5.3.30]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[org_springframework_boot_spring_boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[org_springframework_boot_spring_boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409) ~[org_springframework_boot_spring_boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[org_springframework_boot_spring_boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[org_springframework_boot_spring_boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) ~[org_springframework_boot_spring_boot-2.7.18.jar:2.7.18]
	at com.uber.data.kafka.consumerproxy.UForwarder.main(UForwarder.java:22) ~[libsrc_main.jar:?]
	at com.uber.data.kafka.consumerproxy.testutils.UForwarderStarter.lambda$startUForwarder$0(UForwarderStarter.java:62) ~[integration_test_main.jar:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.RuntimeException: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:62932
	at com.uber.data.kafka.consumerproxy.controller.GrpcServerRunner.start(GrpcServerRunner.java:42) ~[libsrc_main.jar:?]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179) ~[org_springframework_spring_context-5.3.30.jar:5.3.30]
	... 16 more
Caused by: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:62932
	at io.grpc.netty.shaded.io.grpc.netty.NettyServer.start(NettyServer.java:328) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:183) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:92) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at com.uber.data.kafka.consumerproxy.controller.GrpcServerRunner.start(GrpcServerRunner.java:39) ~[libsrc_main.jar:?]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179) ~[org_springframework_spring_context-5.3.30.jar:5.3.30]
	... 16 more
Caused by: java.lang.RuntimeException: Server ports should be set to 0 so that an available port can is assigned to the server. Using a static port 62932 can lead to port collision in CI. For more info, see https://p.uber.com/java-ephemeral-ports
	at sun.nio.ch.Net.bind(Net.java:454) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:448) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227) ~[?:?]
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.netty.shaded.io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io_grpc_grpc_netty_shaded-1.49.2_uber_0.1.jar:?]
	... 1 more
2024-09-17 21:51:06,847 WARN  [Thread-7] com.uber.data.kafka.consumerproxy.testutils.UForwarderStarter UForwarderStarter: Fail to start uforwarder-controller
2024-09-17 21:51:34,613 INFO  [Thread-7-SendThread(localhost:32793)] org.apache.zookeeper.ClientCnxn ClientCnxn: Unable to read additional data from server sessionid 0x1000947d5d70007, likely server has closed socket, closing socket connection and attempting reconnect
2024-09-17 21:51:34,613 INFO  [Thread-7-SendThread(localhost:32793)] org.apache.zookeeper.ClientCnxn ClientCnxn: Unable to read additional data from server sessionid 0x1000947d5d70004, likely server has closed socket, closing socket connection and attempting reconnect
2024-09-17 21:51:34,615 INFO  [main-SendThread(localhost:32793)] org.apache.zookeeper.ClientCnxn ClientCnxn: Unable to read additional data from server sessionid 0x1000947d5d70001, likely server has closed socket, closing socket connection and attempting reconnect
2024-09-17 21:51:34,615 INFO  [Thread-7-SendThread(localhost:32793)] org.apache.zookeeper.ClientCnxn ClientCnxn: Unable to read additional data from server sessionid 0x1000947d5d70006, likely server has closed socket, closing socket connection and attempting reconnect
2024-09-17 21:51:34,613 INFO  [Thread-7-SendThread(localhost:32793)] org.apache.zookeeper.ClientCnxn ClientCnxn: Unable to read additional data from server sessionid 0x1000947d5d70002, likely server has closed socket, closing socket connection and attempting reconnect
2024-09-17 21:51:34,613 INFO  [Thread-7-SendThread(localhost:32793)] org.apache.zookeeper.ClientCnxn ClientCnxn: Unable to read additional data from server sessionid 0x1000947d5d70005, likely server has closed socket, closing socket connection and attempting reconnect
2024-09-17 21:51:34,615 INFO  [Thread-7-SendThread(localhost:32793)] org.apache.zookeeper.ClientCnxn ClientCnxn: Unable to read additional data from server sessionid 0x1000947d5d70003, likely server has closed socket, closing socket connection and attempting reconnect
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.junit.contrib.java.lang.system.EnvironmentVariables (file:/Users/ravi/.java_bazelcache/workspace/bca43ba51d2f68a14cdff6c61f14caa9/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/3rdparty/jvm/com/github/stefanbirkner/_/jvm/v1/com_github_stefanbirkner_system_rules-1.19.0.jar) to field java.util.Collections$UnmodifiableMap.m

FAILURES!!!
Tests run: 0,  Failures: 1

BazelTestRunner exiting with a return value of 1
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2024-09-17 21:51:34 --

================================================================================
INFO: Found 1 test target...
Target //data/kafka/uforwarder:integration_test_main up-to-date:
  bazel-bin/data/kafka/uforwarder/integration_test_main
  bazel-bin/data/kafka/uforwarder/integration_test_main.jar
INFO: Elapsed time: 49.821s, Critical Path: 46.17s
INFO: 5 processes: 3 disk cache hit, 1 internal, 1 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 5 total actions
//data/kafka/uforwarder:integration_test_main                            FAILED in 45.2s
    FAILED  com.uber.data.kafka.consumerproxy.UforwarderIntegrationTests.testKafkaConsumerProxyEnd2EndFlowWithRQAndDLQ (0.0s)
    FAILED  com.uber.data.kafka.consumerproxy.UforwarderIntegrationTests.testKafkaConsumerProxyEnd2EndFlowWithTieredRQ (0.0s)
    FAILED  com.uber.data.kafka.consumerproxy.UforwarderIntegrationTests.testKafkaConsumerProxyEnd2EndFlow (0.0s)
Test cases: finished with 0 passing and 3 failing out of 3 test cases

Executed 1 out of 1 test: 1 fails locally.
INFO: Build Event Protocol files produced successfully.

```

__After:__
```
$ bazel test //data/kafka/uforwarder:integration_test_main --test_filter com.uber.data.kafka.consumerproxy.UforwarderIntegrationTests

//data/kafka/uforwarder:integration_test_main                            PASSED in 213.7s
    PASSED  com.uber.data.kafka.consumerproxy.UforwarderIntegrationTests.testKafkaConsumerProxyEnd2EndFlowWithRQAndDLQ (76.1s)
    PASSED  com.uber.data.kafka.consumerproxy.UforwarderIntegrationTests.testKafkaConsumerProxyEnd2EndFlowWithTieredRQ (74.4s)
    PASSED  com.uber.data.kafka.consumerproxy.UforwarderIntegrationTests.testKafkaConsumerProxyEnd2EndFlow (46.3s)
Test cases: finished with 3 passing and 0 failing out of 3 test cases

Executed 1 out of 1 test: 1 test passes.
INFO: Build Event Protocol files produced successfully.
```